### ISSUE TITLE
Moving a switch toggles it

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf-monitor#24]
Not a huge deal, but when trying to position a switch on the playfield image by left-clicking and dragging, the switch is toggled to the opposite state that it was in. It's as if you right-clicked on it to move it.

Steps to recreate:

Place switch on to playfield image.
Left click + drag switch to a new location.

You have to right-click it to toggle it back off again.

**Comment by kylenahas** [comment]
Going forward, toggling on "Device Inspector" deactivates switch clicking.
